### ISSUE TITLE
Error: Attempting to use a disconnected port object

### ISSUE THREAD

**Issue by kekbait** [urish/web-bluetooth-polyfill#30]
Hi, 
First, thanks a lot for your work !
The extension is throwing this message while trying to connect :

![capture1](https://user-images.githubusercontent.com/26081966/31717827-c5028aa8-b40d-11e7-90de-d5eb4975dad4.PNG)

_Windows Version : 1703 (15063.674)_

```
extensions::messaging:102 Uncaught (in promise) Error: Attempting to use a disconnected port object
    at PortImpl.postMessage (extensions::messaging:102:13)
    at Port.publicClassPrototype.(anonymous function) [as postMessage] (extensions::utils:140:26)
    at Promise (chrome-extension://elnncjplpoecpedhbdfhjkgnakeopmdh/background.js:16:20)
    at new Promise (<anonymous>)
    at nativeRequest (chrome-extension://elnncjplpoecpedhbdfhjkgnakeopmdh/background.js:7:12)
    at startScanning (chrome-extension://elnncjplpoecpedhbdfhjkgnakeopmdh/background.js:106:9)
    at requestDevice (chrome-extension://elnncjplpoecpedhbdfhjkgnakeopmdh/background.js:161:5)
    at port.onMessage.addListener (chrome-extension://elnncjplpoecpedhbdfhjkgnakeopmdh/background.js:333:13)
    at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:140:26)
```

**Comment by urish** [comment]
Thank you very much for the detailed instructions! Can you please send a
Pull Request with these instructions (in README under the Troubleshooting
section)

**Comment by kekbait** [comment]
Sure mate. It's done.

**Comment by urish** [comment]
Thanks a bunch!
